class MarkdownGenerator:
    """
    Converts PR summary dictionary into GitHub Markdown.
    """

    def generate(self, summary):

        markdown = f"""# {summary['title']}

## Description

{summary['description']}

---

## Files Changed

"""

        for file in summary["files_changed"]:
            markdown += f"- {file}\n"

        markdown += f"""

---

## Patch Summary

{summary['patch_summary']}

---

## Validation

{summary['validation']}

---

Generated on: {summary['generated_at']}

Generated by **OpenSourceFix AI**
"""

        return markdown
