"""
pr_generator/pr_writer.py

Generates a professional GitHub pull request description using an LLM.

Output format matches GitHub PR conventions:
- Concise title (fix: <what>)
- Linked issue reference
- Problem / Root Cause / Solution / Testing sections
- Files changed summary
- Checklist

This is what you'd actually submit as a PR to a real open-source project.

Example output
--------------
## Fix: Session token not refreshed after expiry

Closes #1234

### Problem
When a session token expires, `refresh_token()` in `auth/session.py`
returns the old token value without checking expiry, causing downstream
401 errors.

### Root Cause
The `is_expired()` check was missing before the return statement.

### Solution
Added an expiry check at the start of `refresh_token()`. If the token
is expired, `TokenExpiredError` is raised immediately.

### Files Changed
- `auth/session.py` — added expiry check in `refresh_token()`

### Testing
- All existing tests pass
- Added `test_refresh_expired_token` to `tests/test_auth.py`

---
*Generated by OpenSourceFix AI*
"""

import logging
import re
from dataclasses import dataclass

logger = logging.getLogger(__name__)


@dataclass
class PullRequestDescription:
    title: str
    body: str
    issue_number: int
    files_changed: list


class PRWriter:
    """
    Generates a professional PR description using an LLM.

    Args:
        model_client: LLM client with .generate(prompt) -> str
    """

    def __init__(self, model_client):
        self.model = model_client

    def write(
        self,
        issue,
        patch_result,                # PatchResult or MultiFilePatch
        validation_result: dict,
        function_location=None,      # FunctionLocation — optional
    ) -> PullRequestDescription:
        """
        Generate a PR description.

        Args:
            issue:             GitHubIssue dataclass.
            patch_result:      PatchResult or MultiFilePatch.
            validation_result: Output of Validator.validate().
            function_location: FunctionLocation for additional context.

        Returns:
            PullRequestDescription with title and markdown body.
        """
        prompt = self._build_prompt(issue, patch_result, validation_result, function_location)
        try:
            raw = self.model.generate(prompt)
            title, body = self._parse_response(raw, issue)
        except Exception as exc:
            logger.warning("PRWriter LLM call failed: %s. Using template.", exc)
            title, body = self._template_fallback(issue, patch_result, validation_result)

        # Determine files changed
        if hasattr(patch_result, "files_changed"):
            files = patch_result.files_changed
        elif hasattr(patch_result, "target_file"):
            files = [patch_result.target_file]
        else:
            files = []

        logger.info("PRWriter generated PR: %s", title)
        return PullRequestDescription(
            title=title,
            body=body,
            issue_number=issue.number,
            files_changed=files,
        )

    def to_markdown(self, pr: PullRequestDescription) -> str:
        """Format for display or file output."""
        return f"# {pr.title}\n\n{pr.body}"

    # ── private ────────────────────────────────────────────────────────────

    def _build_prompt(self, issue, patch_result, validation_result, location) -> str:
        test_status = "✅ All tests passed" if validation_result.get("status") == "PASS" else "⚠️ Tests not run or failed"

        diff_preview = ""
        if hasattr(patch_result, "diff"):
            diff_preview = patch_result.diff[:800]
        elif hasattr(patch_result, "combined_diff"):
            diff_preview = patch_result.combined_diff()[:800]

        location_note = ""
        if location:
            location_note = f"\nFixed function: `{location.function}()` in `{location.file}`"
            location_note += f"\nRoot cause identified: {location.reason}"

        return f"""You are writing a professional GitHub pull request description.

## Issue #{issue.number}: {issue.title}
{issue.body[:600]}
{location_note}

## Patch Applied
```diff
{diff_preview}
```

## Validation
{test_status}

## Task
Write a professional PR description. Use this exact structure:

<TITLE>fix: <15 words or fewer describing what was fixed></TITLE>

<BODY>
Closes #{issue.number}

### Problem
<2-3 sentences: what was broken and its impact>

### Root Cause
<1-2 sentences: the exact technical cause>

### Solution
<2-3 sentences: what the patch does to fix it>

### Files Changed
<bullet list of files and what changed in each>

### Testing
<describe test results and any new tests>

---
*Generated by OpenSourceFix AI*
</BODY>
"""

    def _parse_response(self, raw: str, issue) -> tuple:
        title_match = re.search(r"<TITLE>(.*?)</TITLE>", raw, re.DOTALL)
        body_match  = re.search(r"<BODY>(.*?)</BODY>", raw, re.DOTALL)
        title = title_match.group(1).strip() if title_match else f"fix: issue #{issue.number}"
        body  = body_match.group(1).strip() if body_match else raw.strip()
        return title, body

    def _template_fallback(self, issue, patch_result, validation_result) -> tuple:
        title = f"fix: {issue.title[:60]}"
        status = validation_result.get("status", "UNKNOWN")
        body = f"""Closes #{issue.number}

### Problem
{issue.body[:300]}

### Solution
Automated patch generated by OpenSourceFix AI.

### Testing
Validation status: {status}

---
*Generated by OpenSourceFix AI*
"""
        return title, body
